app_name = 'carigetir_hr'
app_title = 'Carigetir Hr'
app_publisher = 'CariGetir'
app_description = 'CariGetir V2 carigetir_hr'
app_icon = 'octicon octicon-file-directory'
app_color = 'grey'
app_email = 'info@carigetir.com'
app_license = 'MIT'
